name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-18.04
    container:
      image: ros:melodic
    steps:
      - name: Install basic ROS requirements
        run: |
          apt-get update && \
          apt-get install -y python-catkin-tools python-pip python3-pip && \
          apt-get install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential python-catkin-tools

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/geographiclib_conversions

      - name: Install geographiclib_conversions requirements
        run: ./catkin_ws/src/geographiclib_conversions/scripts/install.sh

      - name: catkin build
        run: source /opt/ros/melodic/setup.bash && cd catkin_ws && catkin build
